"""
Constrained Top-K Beam Search Algorithm for Attack Path Reconstruction.
Combines edge probabilities P(u -> v) with security feasibility verification
to output ranked multi-hop attack trajectories.
"""

from dataclasses import dataclass, field
from typing import List, Optional, Tuple, Dict, Any, Union
import numpy as np
import torch

from src.data.schema import (
    NetworkGraphData,
    EdgeType,
    IDX_TO_EDGE,
    EDGE_TO_IDX,
)
from src.search.feasibility import SecurityConstraintEngine


@dataclass
class PathHopDetail:
    """Detailed metadata for a single step in the predicted attack trajectory."""
    source_idx: int
    target_idx: int
    source_name: str
    target_name: str
    edge_type: str
    probability: float
    description: str


@dataclass
class PredictedAttackPath:
    """A ranked complete attack path generated by the prediction engine."""
    rank: int
    nodes: List[int]
    node_names: List[str]
    confidence_score: float # Geometric mean or cumulative likelihood
    cumulative_prob: float
    hop_count: int
    hops: List[PathHopDetail] = field(default_factory=list)


class ConstrainedBeamSearch:
    """
    Feasibility-Constrained Beam Search for Top-K Attack Path Generation.
    """

    def __init__(
        self,
        beam_width: int = 5,
        max_hops: int = 12,
        min_edge_prob: float = 1e-4,
        constraint_engine: Optional[SecurityConstraintEngine] = None,
    ):
        self.beam_width = beam_width
        self.max_hops = max_hops
        self.min_edge_prob = min_edge_prob
        self.constraint_engine = constraint_engine or SecurityConstraintEngine()

    def search(
        self,
        edge_probs: torch.Tensor,
        adj_tensor: torch.Tensor,
        x_matrix: torch.Tensor,
        source_idx: int,
        target_idx: int,
        node_names: Optional[List[str]] = None,
        top_k: Optional[int] = None,
    ) -> List[PredictedAttackPath]:
        """
        Executes constrained beam search from source_idx to target_idx.

        Args:
            edge_probs: (N, N) matrix of predicted edge likelihoods in [0, 1]
            adj_tensor: (N, N, 16) multi-relational graph tensor
            x_matrix: (N, 20) node feature matrix
            source_idx: Compromised start node
            target_idx: Target crown jewel node
            node_names: Optional list of entity names
            top_k: Number of paths to return (defaults to beam_width)

        Returns:
            List of ranked PredictedAttackPath objects.
        """
        k = top_k or self.beam_width
        num_nodes = edge_probs.shape[0]

        if node_names is None or len(node_names) != num_nodes:
            node_names = [f"Node_{i}" for i in range(num_nodes)]

        # If source is already target
        if source_idx == target_idx:
            return [
                PredictedAttackPath(
                    rank=1,
                    nodes=[source_idx],
                    node_names=[node_names[source_idx]],
                    confidence_score=1.0,
                    cumulative_prob=1.0,
                    hop_count=0,
                    hops=[],
                )
            ]

        # Each beam candidate: (current_path: List[int], log_prob_sum: float, prod_prob: float)
        # Initial beam with start node
        beams: List[Tuple[List[int], float, float]] = [([source_idx], 0.0, 1.0)]
        completed_paths: List[Tuple[List[int], float, float]] = []

        for hop in range(self.max_hops):
            candidates: List[Tuple[List[int], float, float]] = []

            for path, log_prob, prod_prob in beams:
                current_node = path[-1]

                # If already at target, preserve in completed
                if current_node == target_idx:
                    completed_paths.append((path, log_prob, prod_prob))
                    continue

                # Get feasible successors
                valid_succs = self.constraint_engine.get_valid_successors(
                    current_node, x_matrix, adj_tensor, current_path=path
                )

                for next_node in valid_succs:
                    prob = float(edge_probs[current_node, next_node].item())
                    if prob < self.min_edge_prob:
                        # Give small baseline epsilon to topologically valid physical edges
                        prob = max(prob, self.min_edge_prob)

                    new_path = path + [next_node]
                    new_log_prob = log_prob + np.log(prob + 1e-9)
                    new_prod_prob = prod_prob * prob

                    candidates.append((new_path, new_log_prob, new_prod_prob))

            if not candidates:
                break

            # Sort candidates by length-normalized score: log_prob / (len(path) - 1)
            candidates.sort(key=lambda item: item[1] / max(1, len(item[0]) - 1), reverse=True)
            beams = candidates[:self.beam_width]

            # Early stopping if all beams have reached target
            if all(path[-1] == target_idx for path, _, _ in beams):
                for p in beams:
                    if p not in completed_paths:
                        completed_paths.append(p)
                break

        # Collect remaining beams that reached target
        for p in beams:
            if p[0][-1] == target_idx and p not in completed_paths:
                completed_paths.append(p)

        # If no path reached target, fallback to the closest candidate path
        if not completed_paths:
            if beams:
                completed_paths = [beams[0]]
            else:
                completed_paths = [([source_idx], -100.0, 0.0)]

        # Sort completed paths by confidence
        completed_paths.sort(key=lambda item: item[1] / max(1, len(item[0]) - 1), reverse=True)
        unique_paths = []
        seen_seqs = set()
        for p in completed_paths:
            seq_tuple = tuple(p[0])
            if seq_tuple not in seen_seqs:
                seen_seqs.add(seq_tuple)
                unique_paths.append(p)

        results: List[PredictedAttackPath] = []
        for rank_idx, (path_nodes, log_prob, prod_prob) in enumerate(unique_paths[:k]):
            hop_count = max(0, len(path_nodes) - 1)
            # Normalized confidence score in [0.0, 1.0]
            if hop_count > 0:
                geom_mean = np.exp(log_prob / hop_count)
            else:
                geom_mean = 1.0 if path_nodes[0] == target_idx else 0.0

            # Construct hop details
            hops: List[PathHopDetail] = []
            for i in range(hop_count):
                u = path_nodes[i]
                v = path_nodes[i + 1]
                prob = float(edge_probs[u, v].item())

                # Find dominant edge type
                rel_indices = (adj_tensor[u, v] > 0.5).nonzero(as_tuple=True)[0]
                if len(rel_indices) > 0:
                    edge_type_name = IDX_TO_EDGE[int(rel_indices[0].item())].value
                else:
                    edge_type_name = "Connected"

                desc = f"Adversary pivots from {node_names[u]} to {node_names[v]} via {edge_type_name} (Likelihood: {prob*100:.1f}%)"
                hops.append(
                    PathHopDetail(
                        source_idx=u,
                        target_idx=v,
                        source_name=node_names[u],
                        target_name=node_names[v],
                        edge_type=edge_type_name,
                        probability=prob,
                        description=desc,
                    )
                )

            results.append(
                PredictedAttackPath(
                    rank=rank_idx + 1,
                    nodes=path_nodes,
                    node_names=[node_names[idx] for idx in path_nodes],
                    confidence_score=float(geom_mean),
                    cumulative_prob=float(prod_prob),
                    hop_count=hop_count,
                    hops=hops,
                )
            )

        return results
