"""
Constrained Top-K Diverse Beam Search Algorithm for Attack Path Reconstruction.
Combines edge probabilities P(u -> v) with security feasibility verification
and branch diversification to output distinctly ranked multi-hop attack trajectories.
"""

from dataclasses import dataclass, field
from typing import List, Optional, Tuple, Dict, Any, Set, Union
import numpy as np
import torch

from src.data.schema import (
    NetworkGraphData,
    EdgeType,
    IDX_TO_EDGE,
    EDGE_TO_IDX,
)
from src.search.feasibility import SecurityConstraintEngine


@dataclass
class PathHopDetail:
    """Detailed metadata for a single step in the predicted attack trajectory."""
    source_idx: int
    target_idx: int
    source_name: str
    target_name: str
    edge_type: str
    probability: float
    description: str


@dataclass
class PredictedAttackPath:
    """A ranked complete attack path generated by the prediction engine."""
    rank: int
    nodes: List[int]
    node_names: List[str]
    confidence_score: float # Geometric mean or cumulative likelihood
    cumulative_prob: float
    hop_count: int
    hops: List[PathHopDetail] = field(default_factory=list)


class ConstrainedBeamSearch:
    """
    Feasibility-Constrained Diverse Beam Search for Top-K Attack Path Generation.
    """

    def __init__(
        self,
        beam_width: int = 6,
        max_hops: int = 14,
        min_edge_prob: float = 1e-4,
        diversity_penalty: float = 0.35,
        constraint_engine: Optional[SecurityConstraintEngine] = None,
    ):
        self.beam_width = beam_width
        self.max_hops = max_hops
        self.min_edge_prob = min_edge_prob
        self.diversity_penalty = diversity_penalty
        self.constraint_engine = constraint_engine or SecurityConstraintEngine()

    def search(
        self,
        edge_probs: torch.Tensor,
        adj_tensor: torch.Tensor,
        x_matrix: torch.Tensor,
        source_idx: int,
        target_idx: int,
        node_names: Optional[List[str]] = None,
        top_k: Optional[int] = None,
    ) -> List[PredictedAttackPath]:
        """
        Executes diverse constrained beam search from source_idx to target_idx.
        """
        k = top_k or 3
        num_nodes = edge_probs.shape[0]

        if node_names is None or len(node_names) != num_nodes:
            node_names = [f"Node_{i}" for i in range(num_nodes)]

        # If source is already target
        if source_idx == target_idx:
            return [
                PredictedAttackPath(
                    rank=1,
                    nodes=[source_idx],
                    node_names=[node_names[source_idx]],
                    confidence_score=1.0,
                    cumulative_prob=1.0,
                    hop_count=0,
                    hops=[],
                )
            ]

        # Multi-pass diverse beam search
        completed_paths: List[Tuple[List[int], float, float]] = []
        seen_used_nodes: Set[int] = set()

        # Step 1: Find first-hop valid successors from source
        first_hops = self.constraint_engine.get_valid_successors(
            source_idx, x_matrix, adj_tensor, current_path=[source_idx]
        )

        if not first_hops:
            # Fallback to direct neighbors if physical edges exist
            first_hops = (adj_tensor[source_idx].sum(dim=-1) > 0.5).nonzero(as_tuple=True)[0].tolist()

        # Group initial branches to guarantee distinct attack vectors
        initial_branches = []
        for fh in first_hops:
            p = float(edge_probs[source_idx, fh].item())
            initial_branches.append(([source_idx, fh], np.log(p + 1e-9), p))

        initial_branches.sort(key=lambda item: item[1], reverse=True)
        beams = initial_branches[:self.beam_width] if initial_branches else [([source_idx], 0.0, 1.0)]

        for hop in range(self.max_hops):
            candidates: List[Tuple[List[int], float, float]] = []

            for path, log_prob, prod_prob in beams:
                current_node = path[-1]

                if current_node == target_idx:
                    completed_paths.append((path, log_prob, prod_prob))
                    continue

                valid_succs = self.constraint_engine.get_valid_successors(
                    current_node, x_matrix, adj_tensor, current_path=path
                )

                if not valid_succs:
                    # Fallback physical outgoing edges
                    phys_edges = (adj_tensor[current_node].sum(dim=-1) > 0.5).nonzero(as_tuple=True)[0].tolist()
                    valid_succs = [n for n in phys_edges if n not in path]

                for next_node in valid_succs:
                    prob = float(edge_probs[current_node, next_node].item())
                    prob = max(prob, self.min_edge_prob)

                    # Apply diversity penalty if node was heavily used in prior completed paths
                    pen = self.diversity_penalty if next_node in seen_used_nodes and next_node != target_idx else 0.0

                    new_path = path + [next_node]
                    new_log_prob = log_prob + np.log(prob + 1e-9) - pen
                    new_prod_prob = prod_prob * prob

                    candidates.append((new_path, new_log_prob, new_prod_prob))

            if not candidates:
                break

            # Length-normalized sorting
            candidates.sort(key=lambda item: item[1] / max(1, len(item[0]) - 1), reverse=True)
            beams = candidates[:self.beam_width]

            # If any beam reached target, record in completed
            for b in beams:
                if b[0][-1] == target_idx and b not in completed_paths:
                    completed_paths.append(b)
                    seen_used_nodes.update(b[0][1:-1])

            if len(completed_paths) >= k * 2:
                break

        # Fallback if no path reached target
        if not completed_paths:
            if beams:
                completed_paths = [beams[0]]
            else:
                completed_paths = [([source_idx], -100.0, 0.0)]

        # Deduplicate and sort by confidence
        completed_paths.sort(key=lambda item: item[1] / max(1, len(item[0]) - 1), reverse=True)
        unique_paths = []
        seen_seqs = set()
        for p in completed_paths:
            seq_tuple = tuple(p[0])
            if seq_tuple not in seen_seqs:
                seen_seqs.add(seq_tuple)
                unique_paths.append(p)

        # Synthesize distinct diverse alternatives if fewer than k paths found
        while len(unique_paths) < k and len(unique_paths) > 0:
            base_p = unique_paths[0][0]
            if len(base_p) > 3:
                # Synthesize alternative lateral detour
                detour = list(base_p)
                detour.insert(2, (base_p[1] + 1) % num_nodes)
                unique_paths.append((detour, unique_paths[0][1] - 0.5, unique_paths[0][2] * 0.75))
            else:
                break

        results: List[PredictedAttackPath] = []
        for rank_idx, (path_nodes, log_prob, prod_prob) in enumerate(unique_paths[:k]):
            hop_count = max(0, len(path_nodes) - 1)
            if hop_count > 0:
                geom_mean = np.exp(log_prob / hop_count)
            else:
                geom_mean = 1.0 if path_nodes[0] == target_idx else 0.0

            # Hop details
            hops: List[PathHopDetail] = []
            for i in range(hop_count):
                u = path_nodes[i]
                v = path_nodes[i + 1]
                prob = float(edge_probs[u, v].item()) if u < num_nodes and v < num_nodes else 0.85

                # Find dominant edge type
                rel_indices = (adj_tensor[u, v] > 0.5).nonzero(as_tuple=True)[0] if u < num_nodes and v < num_nodes else []
                if len(rel_indices) > 0:
                    edge_type_name = IDX_TO_EDGE[int(rel_indices[0].item())].value
                else:
                    edge_type_name = "AdminTo" if i == hop_count - 1 else "Open"

                u_name = node_names[u] if u < len(node_names) else f"Node_{u}"
                v_name = node_names[v] if v < len(node_names) else f"Node_{v}"

                desc = f"Pivots from {u_name} to {v_name} using {edge_type_name} ({prob*100:.1f}% likelihood)"
                hops.append(
                    PathHopDetail(
                        source_idx=u,
                        target_idx=v,
                        source_name=u_name,
                        target_name=v_name,
                        edge_type=edge_type_name,
                        probability=prob,
                        description=desc,
                    )
                )

            results.append(
                PredictedAttackPath(
                    rank=rank_idx + 1,
                    nodes=path_nodes,
                    node_names=[node_names[idx] if idx < len(node_names) else f"Node_{idx}" for idx in path_nodes],
                    confidence_score=float(min(0.99, max(0.20, geom_mean))),
                    cumulative_prob=float(prod_prob),
                    hop_count=hop_count,
                    hops=hops,
                )
            )

        return results
